Merge from trunk: 220496,220499-220506,220509-220512,220514-220515,220518-220523,220526,220530-220533,220535-220553,220556-220557,220559-220561,220563-220566,220576-220590,220594,220596,220598,220601-220606,220608-220610,220613,220616-220621,220625-220626,220628-220632,220636-220637,220640-220641,220646-220650,220654-220658,220660-220667,220671-220680,220682-220689,220693-220698,220700-220702,220705-220706,220708-220711,220714-220716,220718,220721-220722,220731-220744,220747-220749,220751,220757-220761,220763-220765,220768-220775,220778-220801,220804,220806-220808,220810-220812,220814,220816-220817,220819,220821-220823,220825-220827,220829,220832-220833,220836-220847,220850-220853,220855-220862,220864-220873,220875-220878,220882,220885-220889,220892-220895,220897-220899,220902-220906,220910,220913,220915-220916,220919-220925,220928-220931,220936-220937,220944-220947,220950-220953,220956,220958-220959,220961-220962,220964,220966-220967,220969-220974,220976-220977,220982,220984-220985,220987,220990-220992,220995,220998-220999,221002,221004-221005,221007-221013,221015-221017,221020-221027,221029-221035,221038-221041,221043,221046-221050,221053,221055-221056,221058-221066,221068-221071,221074-221080,221083-221092,221095-221097,221099-221125,221127-221128,221131-221134,221139,221141,221143-221152,221154-221161,221164-221165,221169,221171,221174-221191,221193,221197-221199,221202-221213,221217-221223,221226,221229-221231,221233-221238,221243-221250,221253-221258,221261-221271,221274-221279,221281-221288,221291-221293,221296-221299,221303-221304,221306,221308-221322,221325-221332,221334-221335,221337,221342,221345,221347-221350,221353,221355-221359,221361-221364,221366,221369-221374,221377-221381,221386-221388,221391-221393,221396-221398,221402,221405-221407,221409-221410,221412-221415,221417-221423,221425-221428,221432-221436,221439,221441,221444-221449,221452-221453,221455,221457-221460,221462-221464,221466,221469-221478,221481-221492,221494,221497-221498,221500-221502,221505-221506,221508-221510,221512-221516,221518-221522,221524,221527-221533,221535,221537-221539,221541-221542,221544,221547,221549-221554,221557-221559,221564,221568-221570,221572-221577,221581-221583,221585-221588,221592-221593,221595-221602,221604-221607,221613-221615,221618-221630,221635-221638,221640-221645,221648-221651,221653-221662,221665-221668,221671-221675,221677,221680-221683,221685,221688,221690,221693-221694,221697-221699,221701-221704,221706-221711,221714,221717-221732,221734-221742,221744-221745,221749-221753,221756-221757,221760-221765,221768-221771,221774-221777,221781-221782,221785-221790,221794-221802,221805-221811,221814,221817-221818,221830-221831,221833-221835,221838-221844,221848,221850-221853,221855,221858-221862,221865-221868,221871-221872,221876-221878,221880,221882-221884,221887-221889,221891-221893,221896-221897,221899-221902,221904-221906,221908-221910,221914,221916-221922,221925-221933,221937,221940-221945,221947,221949,221951-221956,221958-221963,221966-221976,221981-221983,221985-221987,221989-221990,221992-221993,221996,221999-222001,222007-222011,222014-222024
git-svn-id: svn+ssh://gcc.gnu.org/svn/gcc/branches/google@224108 138bc75d-0d04-0410-961f-82ee72b054a4

diff --git a/main/gcc/configure b/main/gcc/configure
--- a/main/gcc/configure
+++ b/main/gcc/configure
@@ -4798,9 +4798,15 @@ esac
 case "${target}" in
     # PIC is the default on some targets or must not be used.
     *-*-darwin*)
-	# PIC is the default on this platform
-	# Common symbols not allowed in MH_DYLIB files
-	PICFLAG_FOR_TARGET=-fno-common
+	# For darwin, common symbols are not allowed in MH_DYLIB files
+	case "${CFLAGS}" in
+	  # If we are using a compiler supporting mdynamic-no-pic
+	  # and the option has been tested as safe to add, then cancel
+	  # it here, since the code generated is incompatible with shared
+	  # libs.
+	  *-mdynamic-no-pic*) PICFLAG_FOR_TARGET='-fno-common -mno-dynamic-no-pic' ;;
+	  *) PICFLAG_FOR_TARGET=-fno-common ;;
+	esac
 	;;
     alpha*-dec-osf5*)
 	# PIC is the default.
@@ -8477,7 +8483,7 @@ $as_echo "#define GWINSZ_IN_SYS_IOCTL 1" >>confdefs.h
 fi
 
 for ac_header in limits.h stddef.h string.h strings.h stdlib.h time.h iconv.h \
-		 fcntl.h unistd.h sys/file.h sys/time.h sys/mman.h \
+		 fcntl.h ftw.h unistd.h sys/file.h sys/time.h sys/mman.h \
 		 sys/resource.h sys/param.h sys/times.h sys/stat.h \
 		 direct.h malloc.h langinfo.h ldfcn.h locale.h wchar.h
 do :
@@ -18197,7 +18203,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<_LT_EOF
-#line 18150 "configure"
+#line 18156 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -18303,7 +18309,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<_LT_EOF
-#line 18256 "configure"
+#line 18262 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -24231,6 +24237,70 @@ $as_echo "$gcc_cv_as_alpha_jsrdirect_relocs" >&6; }
 if test $gcc_cv_as_alpha_jsrdirect_relocs = yes; then
 
 $as_echo "#define HAVE_AS_JSRDIRECT_RELOCS 1" >>confdefs.h
+
+fi
+    ;;
+
+  avr-*-*)
+    { $as_echo "$as_me:${as_lineno-$LINENO}: checking assembler for --mlink-relax option" >&5
+$as_echo_n "checking assembler for --mlink-relax option... " >&6; }
+if test "${gcc_cv_as_avr_mlink_relax+set}" = set; then :
+  $as_echo_n "(cached) " >&6
+else
+  gcc_cv_as_avr_mlink_relax=no
+  if test x$gcc_cv_as != x; then
+    $as_echo '.text' > conftest.s
+    if { ac_try='$gcc_cv_as $gcc_cv_as_flags --mlink-relax -o conftest.o conftest.s >&5'
+  { { eval echo "\"\$as_me\":${as_lineno-$LINENO}: \"$ac_try\""; } >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  $as_echo "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
+  test $ac_status = 0; }; }
+    then
+	gcc_cv_as_avr_mlink_relax=yes
+    else
+      echo "configure: failed program was" >&5
+      cat conftest.s >&5
+    fi
+    rm -f conftest.o conftest.s
+  fi
+fi
+{ $as_echo "$as_me:${as_lineno-$LINENO}: result: $gcc_cv_as_avr_mlink_relax" >&5
+$as_echo "$gcc_cv_as_avr_mlink_relax" >&6; }
+if test $gcc_cv_as_avr_mlink_relax = yes; then
+
+$as_echo "#define HAVE_AS_AVR_MLINK_RELAX_OPTION 1" >>confdefs.h
+
+fi
+
+    { $as_echo "$as_me:${as_lineno-$LINENO}: checking assembler for -mrmw option" >&5
+$as_echo_n "checking assembler for -mrmw option... " >&6; }
+if test "${gcc_cv_as_avr_mrmw+set}" = set; then :
+  $as_echo_n "(cached) " >&6
+else
+  gcc_cv_as_avr_mrmw=no
+  if test x$gcc_cv_as != x; then
+    $as_echo '.text' > conftest.s
+    if { ac_try='$gcc_cv_as $gcc_cv_as_flags -mrmw -o conftest.o conftest.s >&5'
+  { { eval echo "\"\$as_me\":${as_lineno-$LINENO}: \"$ac_try\""; } >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  $as_echo "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
+  test $ac_status = 0; }; }
+    then
+	gcc_cv_as_avr_mrmw=yes
+    else
+      echo "configure: failed program was" >&5
+      cat conftest.s >&5
+    fi
+    rm -f conftest.o conftest.s
+  fi
+fi
+{ $as_echo "$as_me:${as_lineno-$LINENO}: result: $gcc_cv_as_avr_mrmw" >&5
+$as_echo "$gcc_cv_as_avr_mrmw" >&6; }
+if test $gcc_cv_as_avr_mrmw = yes; then
+
+$as_echo "#define HAVE_AS_AVR_MRMW_OPTION 1" >>confdefs.h
 
 fi
     ;;
